#define DSSC_SEED "DSSC_SEED"

#define Y_PUT        (char)0x01
#define Y_PLUS       (char)0x02
#define Y_MINUS      (char)0x03
#define Y_MULT       (char)0x04
#define Y_DIV        (char)0x05
#define Y_NEG        (char)0x06
#define Y_PUTIND     (char)0x07
#define Y_PUTMAXIND  (char)0x08
#define Y_XARR       (char)0x09
#define Y_YARR       (char)0x0a
#define Y_X          (char)0x0b
#define Y_Y          (char)0x0c
#define Y_PARAM      (char)0x0d

#define Y_SIN        (char)0x20
#define Y_COS        (char)0x21
#define Y_TAN        (char)0x22
#define Y_ASIN       (char)0x23
#define Y_ACOS       (char)0x24
#define Y_ATAN       (char)0x25
#define Y_ATAN2      (char)0x26
#define Y_EXP        (char)0x27
#define Y_LOG        (char)0x28
#define Y_LOG10      (char)0x29
#define Y_POW        (char)0x2a
#define Y_SQRT       (char)0x2b
#define Y_CBRT       (char)0x2c
#define Y_HYPOT      (char)0x2d
#define Y_EXPM1      (char)0x2e
#define Y_LOG1P      (char)0x2f
#define Y_SINH       (char)0x30
#define Y_COSH       (char)0x31
#define Y_TANH       (char)0x32
#define Y_ASINH      (char)0x33
#define Y_ACOSH      (char)0x34
#define Y_ATANH      (char)0x35
#define Y_FABS       (char)0x36
#define Y_PSI        (char)0x37
#define Y_PSIFN      (char)0x38
#define Y_RAND       (char)0x39
#define Y_THETA      (char)0x3a
#define Y_MAX        (char)0x3b
#define Y_MIN        (char)0x3c
#define Y_XMIN       (char)0x3d
#define Y_XMAX       (char)0x3e
#define Y_YMIN       (char)0x3f
#define Y_YMAX       (char)0x40
